### ISSUE TITLE
Set default values on component

### ISSUE THREAD

**Issue by andyrue** [akserg/ng2-slim-loading-bar#14]
I'd like to be able to set the color and height on the component selector like this:

    <ng2-slim-loading-bar [color]='color' [height]='height'>

`color` and `height` being string variables set in my app component constructor. I see `@Inputs` in the component for those variables so I thought I could do something like that, but it doesn't work. If I set anything like that on the selector nothing loads if I call `this.slimLoadingBarService.start()`, it only works if I don't try to change the color/height. Anyway to do this without having to call `this.slimLoadingBarService.color='blue'`, etc.?

**Comment by akserg** [comment]
I have created [plunker](https://plnkr.co/OykV39) for you to prove all work as expected.

**Comment by andyrue** [comment]
Thanks! I see I was using single quotes instead of double quotes. Thanks for your guidance!
