### ISSUE TITLE
SlimLoadingBarModule incorrectly exports SlimLoadingBarService

### ISSUE THREAD

**Issue by Gustorn** [akserg/ng2-slim-loading-bar#18]
The service export present in the NgModule breaks Angular's module imports:

```ts
exports: [SlimLoadingBarComponent, >> SlimLoadingBarService <<]
```

Services should only be `provided`, not` exported`. For reference see the [Angular 2 Modules FAQ](https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-what-to-export).

This leads to the following error:
```
Unexpected value 'SlimLoadingBarService' exported by the module 'SlimLoadingBarModule'
```

As a temporary workaround, we can use declarations and providers instead of the module import.

EDIT: added description after GitHub mistakenly sent the issue when I only wanted to start a new line

**Comment by akserg** [comment]
Fixed in 2.0.1
