### ISSUE TITLE
Do not exclude .ts files in npm package or fix sourcemaps

### ISSUE THREAD

**Issue by JohannesRudolph** [akserg/ng2-slim-loading-bar#21]
Excluding the `.ts` (_not_ `d.ts`) files from the npm package appears to create problems for builds because the sourcemaps included with the package refer to them. 

Can you either include ts source files or change the generated sourcemaps? I think including the `.ts` source doesn't do too much harm as the project is fairly small, angular itself however chose to use smaller (i.e. useless) sourcemaps that point to the d.ts files. 

See also: 
https://github.com/angular/angular-cli/issues/2364#issuecomment-249822358

**Comment by akserg** [comment]
Hi @JohannesRudolph 
Thank you for the issue. I will have a look.

**Comment by lukaszczernal** [comment]
I experience similar issue. Either `index.ts` is missing in the root folder or `index.js.map` should be removed.

**Comment by akserg** [comment]
Hi @JohannesRudolph 

Please try 2.0.5 and confirm that you issue was fixed.
