### ISSUE TITLE
npm package donesn't include index file

### ISSUE THREAD

**Issue by vsanat** [akserg/ng2-slim-loading-bar#23]
hi Guys,
After doing npm import, I checked the folders, but I couldn't index file that means no -> index.ts or index.d.ts or no index.js file?? can you please tell me what is the problem?

Error: Error: XHR error (404 Not Found) loading http://localhost:8000/node_modules/ng2-slim-loading-bar/index.js(…)

**Comment by akserg** [comment]
Hi @vsanat 
Here is the screenshot of my environment:
![screenshort](https://cloud.githubusercontent.com/assets/1400409/19232963/fa89aeaa-8ee2-11e6-905d-0d60b090fff2.png)
Did you follow the [installation and usage instructions](https://github.com/akserg/ng2-slim-loading-bar#installation)?

**Comment by vsanat** [comment]
hey, thanks for the reply. I got those files after updating to newer version.

**Comment by akserg** [comment]
Cool.
