### ISSUE TITLE
Can't use it with AoT compilation

### ISSUE THREAD

**Issue by dhardtke** [akserg/ng2-slim-loading-bar#24]
Hey,

Your package seems to not be AoT compatible:

`Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function`.

I don't know why it happens but I do know it has to do with the definition of the `.forRoot()` method.

**Comment by akserg** [comment]
Hi @dhardtke 
I'm busy with your issue.

**Comment by scarmarco** [comment]
Same for me!

**Comment by a5hik** [comment]
Same issue here.

**Comment by zk1169** [comment]
Same issue

**Comment by javist7** [comment]
Same issue

**Comment by HartHerbert** [comment]
Somebody got a solution for this ?

**Comment by thanhnhan2tn** [comment]
I have the same issue on used with IONIC 2rc0, Somebody got a solution for this ?

**Comment by HartHerbert** [comment]
not yet. 
And the owner of this hasn't replied yet. 
I've built my own progress bar with the HTML5 <progress> Tag and SCSS style and it's working fine by now. It looks like this one and works very similar, so it's fine for me.

**Comment by jskrzypek** [comment]
@HartHerbert actually it looks like the owner @akserg is working on this on the [aot branch](https://github.com/akserg/ng2-slim-loading-bar/tree/aot), but the fix hasn't been finished/published yet. 

I forked the branch and made some headway on fixing the remaining bugs and I think it's more or less working. You can test it by doing an `npm install jskrzypek/ng2-slim-loading-bar#aot` and then trying to run ngc.

However, we've also decided not to continue using the module/component so I'm not planning to make  a PR or suggest changes. I did, however, make a cleaner branch with only the relevant & substantive changes [here (https://jskrzypek/ng2-slim-loading-bar/tree/aot-clean)](https://jskrzypek/ng2-slim-loading-bar/tree/aot-clean) if anyone wants to pick up where I left off.

**Comment by akserg** [comment]
Hi all,

Please try 2.0.5 and confirm that you issue was fixed.

Big thanks to @jskrzypek.

**Comment by javist7** [comment]
Issue was fixed.
