### ISSUE TITLE
Error: (index):40 Error: (SystemJS) Cannot read property 'toString' of undefined(…)

### ISSUE THREAD

**Issue by eolcum** [akserg/ng2-slim-loading-bar#25]
I can use Module in DEV environment, but after I minimize it with "browserify -s main dist/app/main.js > dist/bundle.js" command, I get the error "(index):40 Error: (SystemJS) Cannot read property 'toString' of undefined(…)" on my PROD env.

It happens after I include the module:
`SlimLoadingBarModule.forRoot()`

**Comment by akserg** [comment]
Hi @eolcum,

Please try 2.0.5 and confirm that you issue was fixed.

**Comment by akserg** [comment]
Please open the new issue if the problem still exists.
