### ISSUE TITLE
Angular version is locked to 2.1.2

### ISSUE THREAD

**Issue by dalibor983** [akserg/ng2-slim-loading-bar#30]
In package.json file angular version is locked to 2.1.2.

Does this library working only with angular 2.1.2?

Current angular version is 2.3.0. I got may warnings and red text in console that complains at angular version in this package.

Can we get slim loader with higher angular version in package.json?

**Comment by john-landgrave** [comment]
@akserg I'm encountering this same issue. I'd love to use your project, but I guess I'm going to fork it and change the dependencies for now and see what happens.

**Comment by john-landgrave** [comment]
Submitted a PR @akserg, can you merge it when you get a chance?

**Comment by akserg** [comment]
Thank you, @john-landgrave.
I have updated the project and published it on NPM with minor changes.
