### ISSUE TITLE
ng2-slim-loading-bar/ 403 (Forbidden)

### ISSUE THREAD

**Issue by Sevensnake** [akserg/ng2-slim-loading-bar#31]
Not sure why I get this error. I am using the systemJs.config
  paths: {
      // paths serve as alias
        'npm:': 'node_modules/',`   'ng2-slim-loading-bar': 'npm:ng2-slim-loading-bar',`

`  'ng2-slim-loading-bar': {
             defaultExtension: 'js'
        },`

**Comment by akserg** [comment]
Did you change the systemjs.config.js to point to the Angular's umd.js file instead of the index.js?
