### ISSUE TITLE
Incorrect slim bar link highlight/underline when using browser back button

### ISSUE THREAD

**Issue by fmorriso** [akserg/ng2-slim-loading-bar#34]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
1. Visit each link in the loading bar by clicking on them.  The order does not matter.
2. Begin clicking the browser's back button.
3. ***ERROR: the previously highlighted/underlined link remains underlined and the new page's corresponding link is not highlighted/underlined.

**Expected/desired behavior**
As the address bar url changes to return to a previous displayed page, the highlight/underline of the currently active progress bar item changes.

**Reproduction of the problem**
Run your online demo using the steps previously described steps.
1. Click on Home
2. Click on Toasty
3. Click on Drag-and-Drop
4. Click your browser's back button.  Drag-and-Drop is still highlighted/underlined.
5. Click your browser's back button again.  Drag-and-Drop is still highlighted/underlined.

**What is the expected behavior?**
As you click the browser's back button, the corresponding slim loading bar link should become highlighted/underlined and the previous slim loading bar link should no longer be highlighted/underlined.

**What is the motivation / use case for changing the behavior?**
To make sure the visual experience of the slim loading bar matches what is happening in the brower's address bar url.

**Please tell us about your environment:**
(your built-in demo)

* **ng2-slim-loading-bar version:** x.x.x
(whatever version of your tool you use in your own online demo)
* **Angular version:** 2.X.X
 
* **Browser:** [all | Chrome 55 | Firefox 50 | IE 11 | Edge
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5] 
(whatever you use in your online demo)

**Comment by akserg** [comment]
Hi @fmorriso,

There is the problem in the demo project. Why did you create the issue in this one?

**Comment by fmorriso** [comment]
Brain fart on my part. Closing.
