### ISSUE TITLE
How to change the speed of progressbar?

### ISSUE THREAD

**Issue by oztek22** [akserg/ng2-slim-loading-bar#37]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x] feature request
```

**Current behavior**
Couldn't find setting to modify speed.

**Expected/desired behavior**
feature which allow me to change the speed of progressbar

**Please tell us about your environment:**

* **ng2-slim-loading-bar version:** 2.3.0

* **Angular version:** 2.4.0
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

**Comment by mjhugo** [comment]
you can set the interval, e.g.

```typescript
        this.slimLoadingBarService.interval = 50;
        this.slimLoadingBarService.start(() => {
           //...
```

**Comment by akserg** [comment]
Hi @oztek22 

Are you happy with solution @mjhugo mentioned above?

**Comment by oztek22** [comment]
@mjhugo thanks and @akserg yes I'm happy with the solution. So, I'm closing my question.

**Comment by akserg** [comment]
Ok.
