### ISSUE TITLE
Update to work in Angular 2.4.7. Error: No provider for EventEmitter!

### ISSUE THREAD

**Issue by thecritic** [akserg/ng2-slim-loading-bar#38]
**I'm submitting a ...** 
```
[X] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
Not working due to error `No provider for EventEmitter!`
Probably related to #32

**Expected/desired behavior**
Should be working in angular2 v 2.4.7

* **ng2-slim-loading-bar version:** 2.X.X, 2.2.0

* **Angular version:** 2.4.7
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by akserg** [comment]
Fixed in 2.4.0
