### ISSUE TITLE
Question about AoT

### ISSUE THREAD

**Issue by Richie765** [akserg/ng2-slim-loading-bar#39]
Thanks for sharing these great ng2 components. Forgive me if this is a silly question. I'm still learning Angular which sometimes gives me a hard time.

When I look in `src/slim-loading-bar.component.js` I can see the template HTML code in there. I can also find it in `bundles/index.umd.js` as well as in my end product (built with `ng built --prod --aot`).

I think that means that `ngc` didn't compile the template and it still needs to be compiled, probably in the browser. Which means slower startup times and the overhead of including the compiler client-side.

The templates of my own app-components cannot be found in the generated code, they seem to be compiled into JavaScript.

Since you know a lot more about Angular 2 than me. Is this correct? Is there a way to optimize this process?

**Comment by Richie765** [comment]
After investigating more, this seems to be an issue with Angular. It doesn't strip the Metadata even-though it's no longer needed. So it's not an issue with your package.

**Comment by akserg** [comment]
Hi @Richie765 
Interesting points. I will have a look.
