### ISSUE TITLE
Bundle not working with angular-rc.1

### ISSUE THREAD

**Issue by Petitt88** [akserg/ng2-slim-loading-bar#5]
Is this supposed to work with angular-rc.1? I can't get it to work despite the docs.

I'm trying to use the `bundles/ng2-slim-loading-bar.min.js`file which I managed to get loaded with systemjs, however this file still has dependencies from the angular-beta version `"angular2/core", "angular2/src/facade/lang", "angular2/common"`.

**Comment by akserg** [comment]
Sorry, my bad.

I forget cleaned the **node_modules** folder as the result it keeps the new and old **angular** 2 folders. That was messy.

Fixed in v **1.2.3**.

**Comment by Petitt88** [comment]
Thank you, now it works!
