### ISSUE TITLE
Angular 5 support.

### ISSUE THREAD

**Issue by aniliht** [akserg/ng2-slim-loading-bar#65]
I'm submitting a ... (check one with "x")

[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[x ] feature request

The package seems to be working fine with Angular 5.   Can you could just update the dependencies so that npm shrinkwrap won't complain?  Thank you.

**Comment by aniliht** [comment]
Here is the output I receive from npm shrinkwrap that may be helpful:

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Developer\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "shrinkwrap"
npm ERR! node v6.11.3
npm ERR! npm  v4.2.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! peer invalid: `@angular/core@^2.4.7 || ^4.0.0, required by ng2-slim-loading-bar@4.0.0`
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Developer\AppData\Roaming\npm-cache\_logs\2017-12-04T16_30_18_779Z-debug.log

**Comment by tigredonorte** [comment]
i need this upgrade too.

**Comment by christianulson** [comment]
me too

**Comment by RuiEEE** [comment]
me three

**Comment by fengerzh** [comment]
please

**Comment by rafalkasa** [comment]
When do you plan to release the angular 5 version ?

**Comment by hikirsch** [comment]
i would volunteer to do this upgrade if i can get some sort of acknowledge from a maintainer prior just in case someone else hasn't started

**Comment by fengerzh** [comment]
@hikirsch You can fork it and just try to upgrade to Angular 5 and see if there is any problem. If no problem, you can raise a PR in your fork.

**Comment by robvaneck** [comment]
im also getting a
```
ng2-slim-loading-bar@4.0.0 requires a peer of @angular/core@^2.4.7 || ^4.0.0 but none was installed.
```
when doing npm install.. please update :)

**Comment by hikirsch** [comment]
oh crap this is my bad, i completely forgot i volunteered to do this and i definitely still want to fix this. we just pushed our release out a couple of days ago so i have time now to do this in the next day. stay tuned.

**Comment by fengerzh** [comment]
Well, actually I've abandon this package, as it seems nobody will maintain it. There are tons of other packages in Github can do the loading bar things, no need to stick to this one.

**Comment by hikirsch** [comment]
so ya this actually became a little bit more complicated because of how old some packages are in this repo - i agree with @fengerzh, best to probably switch at this point since there are many others. i am chosing https://aitboudad.github.io/ngx-loading-bar/
