### ISSUE TITLE
How to implement with angular-cli?

### ISSUE THREAD

**Issue by josepoma** [akserg/ng2-slim-loading-bar#9]
**Mi system-config.ts:**

const packages: any = {
  "ng2-slim-loading-bar": {
    "defaultExtension": "js"
  }
};

const cliSystemConfigPackages: any = {};
barrels.forEach((barrelName: string) => {
  cliSystemConfigPackages[barrelName] = { main: 'index' };  
});

System.config({
  map: {
    '@angular': 'vendor/@angular',
    'rxjs': 'vendor/rxjs',
    'main': 'main.js',
    '@vaadin': 'vendor/@vaadin',
    'ng2-slim-loading-bar':'node_modules/ng2-slim-loading-bar'    
  },
  packages:cliSystemConfigPackages  
});

System.config({ map, packages });

**Error :** zone.js:101 GET http://localhost:4200/node_modules/ng2-slim-loading-bar 404 (Not Found)
zone.js:461 Unhandled Promise rejection: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/ng2-slim-loading-bar
	    at XMLHttpRequest.wrapFn [as _onreadystatechange] (http://localhost:4200/vendor/zone.js/dist/zone.js:769:30)
	    at ZoneDelegate.invokeTask (http://localhost:4200/vendor/zone.js/dist/zone.js:356:38)
	    at Zone.runTask (http://localhost:4200/vendor/zone.js/dist/zone.js:256:48)
	    at XMLHttpRequest.ZoneTask.invoke (http://localhost:4200/vendor/zone.js/dist/zone.js:423:34)
	Error loading http://localhost:4200/node_modules/ng2-slim-loading-bar as "ng2-slim-loading-bar" from http://localhost:4200/main.js ; Zone: <root> ; Task: Promise.then ; Value: Error: Error: XHR error (404 Not Found) loading http://localhost:4200/node_modules/ng2-slim-loading-bar(…)

**Comment by akserg** [comment]
Hi @josepoma 
I have updated the project. Please look at README. The working configuration for you case must look like that:
System.config({
    map: {
        'ng2-slim-loading-bar': 'node_modules/ng2-slim-loading-bar'
    },
    packages: {
        'ng2-slim-loading-bar':  { main: 'index.js',  defaultExtension: 'js' },
    }
});

**Comment by Neill83** [comment]
I had the same problem. In your angular-cli-build.js you have to add the following line to `vendorNpmFiles`.

it would look like:

```
vendorNpmFiles: [
      'ng2-slim-loading-bar/**/*.+(js|js.map)',
     .... more vendor files here
    ],
```

**Comment by akserg** [comment]
Hi @josepoma 
Can I close this issue?
